SELECT A.CAR_ID, A.CAR_TYPE,
       ROUND(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C  ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_ID NOT IN (
    SELECT B.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE END_DATE > TO_DATE('2022-11-01', 'YYYY-MM-DD') AND START_DATE < TO_DATE('2022-12-01', 'YYYY-MM-DD')
)
AND A.CAR_TYPE IN ('세단', 'SUV')
AND C.DURATION_TYPE = '30일 이상'
GROUP BY A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, C.DISCOUNT_RATE
HAVING ROUND(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) >= 500000 
   AND ROUND(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;