SELECT 
    MEMBER_NAME
    , REVIEW_TEXT
    , TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD')
FROM (
    SELECT
        A.MEMBER_NAME
        , B.REVIEW_TEXT
        , B.REVIEW_DATE
    FROM MEMBER_PROFILE A, REST_REVIEW B
    WHERE A.MEMBER_ID = B.MEMBER_ID
      AND B.MEMBER_ID IN 
                     (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID
                      HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM REST_REVIEW GROUP BY MEMBER_ID))
) B
ORDER BY B.REVIEW_DATE
